[mod_opusfile] fix type errors
Since the last round of changes it fails to compile:

mod_opusfile.c: In function 'decode_stream_cb':
mod_opusfile.c:933:143: error: format '%lx' expects argument of type 'long unsigned int', but argument 8 has type 'switch_thread_id_t' {aka 'struct __pthread *'} [-Werror=format=]
  933 |                 switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "[OGG/OPUS Stream Decode] decode_stream_cb(): switch_thread_self(): %lx\n",  switch_thread_self());
      |                                                                                                                                             ~~^      ~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                               |      |
      |                                                                                                                                               |      switch_thread_id_t {aka struct __pthread *}
      |                                                                                                                                               long unsigned int

Address this by applying the same casts that are also used in
src/mod/formats/mod_sndfile/test/test_sndfile.c already.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>